a=9

try:
    print(x)
except: 
    print("Error.")
else:
    print("No errors.")
finally:
    print("Exception test complete.")
